# Generated by Django 4.2.5 on 2024-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_area', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_beds', models.PositiveSmallIntegerField()),
                ('hotel_accommodates', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hotel_star_rating', models.PositiveSmallIntegerField(default=0)),
                ('hotel_description', models.TextField(blank=True, null=True)),
                ('hotel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_hotel_image', models.ImageField(upload_to='hotel_images/')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_amenities', models.ManyToManyField(to='apphotelapi.amenity')),
                ('images', models.ManyToManyField(to='apphotelapi.hotelimage')),
            ],
        ),
    ]
